# Generated by Django 5.0.6 on 2025-11-18 04:44

import django.db.models.deletion
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorApp', '0003_category_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField()),
                ('course_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module', to='instructorApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('video', embed_video.fields.EmbedVideoField()),
                ('module_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='instructorApp.module')),
            ],
        ),
    ]
