# Generated by Django 4.1.2 on 2025-11-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorApp', '0004_module_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
