# Generated by Django 5.2.8 on 2025-11-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructorApp', '0006_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='course_intance',
            new_name='course_instance',
        ),
    ]
