# Generated by Django 5.2.8 on 2025-11-22 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructorApp', '0008_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='course_instance',
            new_name='cart_instance',
        ),
    ]
