# Generated by Django 5.2.8 on 2025-11-24 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructorApp', '0010_remove_order_cart_instance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='callableourse_instance',
            new_name='course_instance',
        ),
    ]
